<?php
if (!defined('APP_NAME')) {
    die('Unauthorized access.');
}

if (!function_exists('crmIsSuperAdminRole') || !crmIsSuperAdminRole()) {
    die('Access denied. Super Admin only.');
}

if (!function_exists('demoResetTableColumns')) {
    function demoResetTableColumns(PDO $pdo, string $table): array
    {
        static $cache = [];
        if (isset($cache[$table])) {
            return $cache[$table];
        }
        try {
            $safeTable = '`' . str_replace('`', '``', $table) . '`';
            $rows = $pdo->query('SHOW COLUMNS FROM ' . $safeTable)->fetchAll(PDO::FETCH_ASSOC) ?: [];
            $cache[$table] = $rows;
            return $rows;
        } catch (Throwable $e) {
            $cache[$table] = [];
            return [];
        }
    }
}

if (!function_exists('demoResetFirstEnumValue')) {
    function demoResetFirstEnumValue(string $type): string
    {
        if (!preg_match("/^enum\((.*)\)$/i", $type, $m)) {
            return '';
        }
        $raw = trim((string)($m[1] ?? ''));
        if ($raw === '') {
            return '';
        }
        $parts = str_getcsv($raw, ',', "'");
        return trim((string)($parts[0] ?? ''));
    }
}

if (!function_exists('demoResetFallbackValue')) {
    function demoResetFallbackValue(array $col)
    {
        $type = strtolower((string)($col['Type'] ?? ''));
        if (strpos($type, 'int') !== false || strpos($type, 'decimal') !== false || strpos($type, 'float') !== false || strpos($type, 'double') !== false) {
            return 0;
        }
        if (strpos($type, 'datetime') !== false || strpos($type, 'timestamp') !== false) {
            return date('Y-m-d H:i:s');
        }
        if ($type === 'date' || strpos($type, 'date') !== false) {
            return date('Y-m-d');
        }
        if ($type === 'time' || strpos($type, 'time') !== false) {
            return date('H:i:s');
        }
        if (strpos($type, 'json') !== false) {
            return '{}';
        }
        if (strpos($type, 'enum(') === 0) {
            $first = demoResetFirstEnumValue($type);
            return $first !== '' ? $first : '';
        }
        return '';
    }
}

if (!function_exists('demoResetInsertAdaptive')) {
    function demoResetInsertAdaptive(PDO $pdo, string $table, array $preferred = []): int
    {
        $columns = demoResetTableColumns($pdo, $table);
        if (empty($columns)) {
            return 0;
        }

        $row = [];
        foreach ($columns as $col) {
            $field = (string)($col['Field'] ?? '');
            if ($field === '') {
                continue;
            }
            $isAuto = stripos((string)($col['Extra'] ?? ''), 'auto_increment') !== false;
            if ($isAuto) {
                continue;
            }

            if (array_key_exists($field, $preferred)) {
                $row[$field] = $preferred[$field];
                continue;
            }

            if (($col['Default'] ?? null) !== null) {
                continue;
            }

            $nullable = strtoupper((string)($col['Null'] ?? 'NO')) === 'YES';
            if ($nullable) {
                continue;
            }

            $row[$field] = demoResetFallbackValue($col);
        }

        if (empty($row)) {
            return 0;
        }

        $safeTable = '`' . str_replace('`', '``', $table) . '`';
        $fields = array_keys($row);
        $fieldSql = implode(',', array_map(static function ($f) {
            return '`' . str_replace('`', '``', $f) . '`';
        }, $fields));
        $valueSql = implode(',', array_fill(0, count($fields), '?'));

        $st = $pdo->prepare('INSERT INTO ' . $safeTable . ' (' . $fieldSql . ') VALUES (' . $valueSql . ')');
        $st->execute(array_values($row));
        return (int)$pdo->lastInsertId();
    }
}

if (!function_exists('demoResetRunReseed')) {
    function demoResetRunReseed(PDO $pdo): array
    {
        $today = date('Y-m-d');
        $now = date('Y-m-d H:i:s');
        $thisMonth = (int)date('n');
        $thisYear = (int)date('Y');

        $sampleUserId = 0;
        $sampleBranchId = 0;
        try {
            $sampleUserId = (int)($pdo->query('SELECT id FROM users ORDER BY id ASC LIMIT 1')->fetchColumn() ?: 0);
            $sampleBranchId = (int)($pdo->query('SELECT id FROM branches ORDER BY id ASC LIMIT 1')->fetchColumn() ?: 0);
        } catch (Throwable $e) {
            $sampleUserId = 0;
            $sampleBranchId = 0;
        }

        $leadId = demoResetInsertAdaptive($pdo, 'leads', [
            'name' => 'Demo Lead',
            'phone' => '9000000001',
            'email' => 'demo.lead@example.com',
            'status' => 'new',
            'source' => 'demo',
            'remarks' => 'Generated by demo reset reseed.',
            'branch_id' => $sampleBranchId > 0 ? $sampleBranchId : 1,
            'assigned_to' => $sampleUserId > 0 ? $sampleUserId : 1,
            'created_by' => $sampleUserId > 0 ? $sampleUserId : 1,
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $enquiryId = demoResetInsertAdaptive($pdo, 'enquiries', [
            'name' => 'Demo Enquiry',
            'phone' => '9000000002',
            'email' => 'demo.enquiry@example.com',
            'status' => 'new',
            'source' => 'demo',
            'branch_id' => $sampleBranchId > 0 ? $sampleBranchId : 1,
            'handled_by' => $sampleUserId > 0 ? $sampleUserId : 1,
            'created_by' => $sampleUserId > 0 ? $sampleUserId : 1,
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $registrationId = demoResetInsertAdaptive($pdo, 'registrations', [
            'registration_no' => 'DEMO-' . date('Ymd-His'),
            'student_name' => 'Demo Student',
            'phone' => '9000000003',
            'email' => 'demo.student@example.com',
            'status' => 'draft',
            'registration_status' => 'draft',
            'branch_id' => $sampleBranchId > 0 ? $sampleBranchId : 1,
            'assigned_to' => $sampleUserId > 0 ? $sampleUserId : 1,
            'created_by' => $sampleUserId > 0 ? $sampleUserId : 1,
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $followupId = demoResetInsertAdaptive($pdo, 'enquiry_followups', [
            'enquiry_id' => $enquiryId > 0 ? $enquiryId : 1,
            'branch_id' => $sampleBranchId > 0 ? $sampleBranchId : 1,
            'created_by' => $sampleUserId > 0 ? $sampleUserId : 1,
            'status' => 'pending',
            'followup_date' => $today,
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $paymentId = demoResetInsertAdaptive($pdo, 'registration_payments', [
            'registration_id' => $registrationId > 0 ? $registrationId : 1,
            'branch_id' => $sampleBranchId > 0 ? $sampleBranchId : 1,
            'created_by' => $sampleUserId > 0 ? $sampleUserId : 1,
            'amount' => 5000,
            'payment_date' => $today,
            'status' => 'paid',
            'approval_status' => 'approved',
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $targetId = demoResetInsertAdaptive($pdo, 'monthly_targets', [
            'user_id' => $sampleUserId > 0 ? $sampleUserId : 1,
            'branch_id' => $sampleBranchId > 0 ? $sampleBranchId : 1,
            'target_month' => $thisMonth,
            'target_year' => $thisYear,
            'target_amount' => 75000,
            'incentive_percent' => 10,
            'status' => 'active',
            'created_by' => $sampleUserId > 0 ? $sampleUserId : 1,
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $notificationId = demoResetInsertAdaptive($pdo, 'user_notifications', [
            'user_id' => $sampleUserId > 0 ? $sampleUserId : 1,
            'title' => 'Demo reset completed',
            'message' => 'Sample demo data has been reseeded successfully.',
            'type' => 'info',
            'is_read' => 0,
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        return [
            'lead' => $leadId,
            'enquiry' => $enquiryId,
            'registration' => $registrationId,
            'followup' => $followupId,
            'payment' => $paymentId,
            'target' => $targetId,
            'notification' => $notificationId,
        ];
    }
}

$resetFlash = $_SESSION['demo_reset_flash'] ?? null;
if (isset($_SESSION['demo_reset_flash'])) {
    unset($_SESSION['demo_reset_flash']);
}

$resetTables = [
    'registration_payments',
    'registrations',
    'enquiry_followups',
    'enquiries',
    'leads',
    'monthly_targets',
    'user_notifications',
    'audit_logs',
];

$existingResetTables = [];
foreach ($resetTables as $table) {
    if (function_exists('crmTableExists') && crmTableExists($pdo, $table)) {
        $existingResetTables[] = $table;
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['run_demo_reset'])) {
    $token = (string)($_POST['csrf_token'] ?? '');
    $confirmText = trim((string)($_POST['confirm_text'] ?? ''));
    $acknowledge = isset($_POST['confirm_irreversible']) ? (string)$_POST['confirm_irreversible'] : '';
    $reseedAfterReset = isset($_POST['reseed_demo_data']) ? (string)$_POST['reseed_demo_data'] : '';

    if (!function_exists('verifyCSRF') || !verifyCSRF($token)) {
        $_SESSION['demo_reset_flash'] = ['type' => 'error', 'text' => 'Invalid request token. Please retry.'];
        header('Location: index.php?page=system/demo_reset');
        exit;
    }

    if (strtoupper($confirmText) !== 'RESET DEMO') {
        $_SESSION['demo_reset_flash'] = ['type' => 'error', 'text' => 'Type exactly RESET DEMO to proceed.'];
        header('Location: index.php?page=system/demo_reset');
        exit;
    }

    if ($acknowledge !== '1') {
        $_SESSION['demo_reset_flash'] = ['type' => 'error', 'text' => 'Please confirm that this action cannot be undone.'];
        header('Location: index.php?page=system/demo_reset');
        exit;
    }

    if (empty($existingResetTables)) {
        $_SESSION['demo_reset_flash'] = ['type' => 'error', 'text' => 'No reset tables were found in this database.'];
        header('Location: index.php?page=system/demo_reset');
        exit;
    }

    $resetDone = 0;
    $reseedSummary = [];
    try {
        @set_time_limit(120);
        $pdo->beginTransaction();
        $pdo->exec('SET FOREIGN_KEY_CHECKS = 0');

        foreach ($existingResetTables as $table) {
            $safeTable = '`' . str_replace('`', '``', $table) . '`';
            $pdo->exec('TRUNCATE TABLE ' . $safeTable);
            $resetDone++;
        }

        if ($reseedAfterReset === '1') {
            $reseedSummary = demoResetRunReseed($pdo);
        }

        $pdo->exec('SET FOREIGN_KEY_CHECKS = 1');
        $pdo->commit();

        if (function_exists('crmAuditInsert')) {
            $auditAction = 'Demo reset executed. Cleared tables: ' . implode(', ', $existingResetTables);
            if ($reseedAfterReset === '1') {
                $createdCount = 0;
                foreach ($reseedSummary as $id) {
                    if ((int)$id > 0) {
                        $createdCount++;
                    }
                }
                $auditAction .= '. Reseed: enabled, created rows: ' . $createdCount;
            }
            crmAuditInsert($pdo, [
                'table_name' => 'system',
                'record_id' => 0,
                'action' => $auditAction,
            ]);
        }

        $msg = 'Demo reset completed. Cleared ' . $resetDone . ' table(s).';
        if ($reseedAfterReset === '1') {
            $createdCount = 0;
            foreach ($reseedSummary as $id) {
                if ((int)$id > 0) {
                    $createdCount++;
                }
            }
            $msg .= ' Reseed enabled: ' . $createdCount . ' sample row group(s) created.';
        }
        $_SESSION['demo_reset_flash'] = ['type' => 'success', 'text' => $msg];
        header('Location: index.php?page=system/demo_reset');
        exit;
    } catch (Throwable $e) {
        try {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }
            $pdo->exec('SET FOREIGN_KEY_CHECKS = 1');
        } catch (Throwable $inner) {
            // no-op
        }

        $_SESSION['demo_reset_flash'] = ['type' => 'error', 'text' => 'Demo reset failed: ' . $e->getMessage()];
        header('Location: index.php?page=system/demo_reset');
        exit;
    }
}
?>

<style>
.demo-reset-wrap{max-width:1140px;margin:0 auto;display:grid;gap:14px;}
.demo-card{background:#fff;border:1px solid #f0cddd;border-radius:14px;box-shadow:0 9px 24px rgba(15,23,42,.06);}
.demo-hero{padding:20px 22px;background:linear-gradient(140deg,#fff4f7 0%,#fff 62%);}
.demo-title{margin:0;color:#1f2a44;font-size:1.7rem !important;font-weight:800;display:flex;align-items:center;gap:10px;}
.demo-title i{color:#d81b60;}
.demo-sub{margin:8px 0 0;color:#5c667d;font-weight:600;}
.demo-alert{border-radius:12px;padding:11px 14px;font-weight:700;border:1px solid;}
.demo-alert.success{background:#f2fff6;border-color:#c9efd8;color:#146c43;}
.demo-alert.error{background:#fff1f1;border-color:#f3c9c9;color:#9d2222;}
.demo-body{padding:18px 20px;}
.demo-label{display:block;margin-bottom:6px;font-weight:800;color:#33415d;}
.demo-input{width:100%;max-width:360px;border:1px solid #e8bfd2;border-radius:10px;padding:10px 12px;font-weight:700;}
.demo-input:focus{outline:none;border-color:#dd3b7a;box-shadow:0 0 0 3px rgba(221,59,122,.14);}
.demo-btn{display:inline-flex;align-items:center;gap:8px;border:1px solid #d72a6d;border-radius:11px;padding:10px 16px;background:linear-gradient(135deg,#eb1f73,#d81b60);color:#fff;font-weight:800;text-decoration:none;}
.demo-note{color:#6b7280;font-size:.9rem !important;}
.demo-list{margin:0;padding-left:18px;color:#3f4c66;line-height:1.6;}
.demo-danger{border-color:#f3c4d1;background:linear-gradient(180deg,#fff9fb 0%,#fff 35%);}
.demo-form{max-width:520px;}
.demo-check-row{
  display:flex !important;
  justify-content:flex-start !important;
  align-items:flex-start;
  gap:10px;
  margin-top:12px;
  padding:10px 12px;
  border:1px solid #f2d5e1;
  border-radius:10px;
  background:#fff;
  width:100%;
  max-width:520px;
  box-sizing:border-box;
}
.demo-check-row input[type="checkbox"]{
  width:18px !important;
  height:18px !important;
  min-width:18px !important;
  margin:2px 0 0 0 !important;
  padding:0 !important;
  accent-color:#d81b60;
  flex:0 0 auto !important;
  position:static !important;
}
.demo-check-label{
  margin:0 !important;
  display:block !important;
  color:#3f4c66;
  font-weight:700;
  line-height:1.4;
  flex:1 1 auto;
  position:static !important;
}
.demo-opt{margin-top:12px;display:flex;align-items:flex-start;gap:10px;padding:10px 12px;border:1px dashed #e8bfd2;border-radius:10px;background:#fff;}
.demo-opt input[type="checkbox"]{width:18px;height:18px;min-width:18px;margin:2px 0 0 0;accent-color:#d81b60;}
.demo-opt span{color:#3f4c66;font-weight:700;line-height:1.4;}
</style>

<div class="container-fluid py-3">
    <div class="demo-reset-wrap">
        <div class="demo-card demo-hero">
            <h3 class="demo-title"><i class="fas fa-undo-alt"></i>Demo Reset</h3>
            <p class="demo-sub">Super Admin only. Clears transactional demo data and keeps setup/master configuration intact.</p>
        </div>

        <?php if (is_array($resetFlash) && !empty($resetFlash['text'])): ?>
            <div class="demo-alert <?= (($resetFlash['type'] ?? '') === 'error') ? 'error' : 'success' ?>">
                <?= htmlspecialchars((string)$resetFlash['text']) ?>
            </div>
        <?php endif; ?>

        <div class="demo-card demo-body">
            <h5 style="margin:0 0 10px;color:#1f2a44;font-weight:800;">Tables Included In Reset</h5>
            <?php if (empty($existingResetTables)): ?>
                <p class="demo-note" style="margin:0;">No target tables found in current database.</p>
            <?php else: ?>
                <ul class="demo-list">
                    <?php foreach ($existingResetTables as $table): ?>
                        <li><?= htmlspecialchars($table) ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>

        <div class="demo-card demo-body demo-danger">
            <h5 style="margin:0 0 10px;color:#9d1f3f;font-weight:800;">Danger Zone</h5>
            <p class="demo-note" style="margin-top:0;">This operation is irreversible for current demo data. Type <b>RESET DEMO</b> to confirm.</p>

            <form method="post" action="index.php?page=system/demo_reset" autocomplete="off" class="demo-form">
                <input type="hidden" name="csrf_token" value="<?= htmlspecialchars((string)generateCSRF()) ?>">
                <label class="demo-label" for="confirm_text">Confirmation Text</label>
                <input type="text" id="confirm_text" name="confirm_text" class="demo-input" placeholder="Type RESET DEMO" required>
                <div class="demo-check-row">
                    <input type="checkbox" id="confirm_irreversible" name="confirm_irreversible" value="1" required>
                    <label class="demo-check-label" for="confirm_irreversible">I understand this action cannot be undone.</label>
                </div>
                <label class="demo-opt" for="reseed_demo_data">
                    <input type="checkbox" id="reseed_demo_data" name="reseed_demo_data" value="1" checked>
                    <span>Reseed sample demo data after reset (recommended).</span>
                </label>
                <div style="margin-top:12px;">
                    <button type="submit" name="run_demo_reset" value="1" class="demo-btn">
                        <i class="fas fa-bolt"></i>Run Demo Reset
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
